// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxbtopbnwtuzcgksvpby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4YnRvcGJud3R1emNna3N2cGJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NTc1MzMsImV4cCI6MjA2ODIzMzUzM30.UYGhF22yNtQyeK0Tn_JxG3-czBKfY7qh13rXU8YyvVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});