name: Supabase Keep Alive

on:
  schedule:
    - cron: "0 0 */3 * *" # every 3 days
  workflow_dispatch: # allows manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Supabase awake
        run: |
          echo "Running Supabase keep-alive..."
          curl -s -X POST \
            -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"query":"select * from keep_alive limit 1;"}' \
            "${{ secrets.SUPABASE_URL }}/rest/v1/rpc"
