name: Supabase Keep Alive

on:
  schedule:
    - cron: "0 0 */3 * *" # every 3 days
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Supabase awake
        run: |
          echo "Running Supabase keep-alive..."
          RESPONSE=$(curl -s -X GET \
            -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            "${{ secrets.SUPABASE_URL }}/rest/v1/keep_alive?select=*")
          echo "Supabase responded with:"
          echo "$RESPONSE"
